apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abac-webhook-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: abac-webhook-role
subjects:
- kind: ServiceAccount
  name: abac-webhook-sa
  namespace: authzforce
