apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abac-webhook-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
- apiGroups: ["admission.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
